#spring.application.name=gateway
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/paybank
#spring.datasource.username=root
#spring.datasource.password=Bigdev@99

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.aop=DEBUG
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

  #spring.data.rest.base-path=/api

  #spring.security.user.name=user
  #spring.security.user.password=user

#server.port = 8080
#
#spring.cloud.discovery.enabled=true
#eureka.client.service-url.defaultZone=http://localhost:8761
#
#spring.cloud.gateway.routes[0].id=submission-service
#spring.cloud.gateway.routes[0].uri=lb://submission-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/submission-service/**
#
#spring.cloud.gateway.routes[1].id=quiz-service
#spring.cloud.gateway.routes[1].uri=lb://quiz-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/quiz-service/**
#
#spring.cloud.gateway.routes[2].id=question-service
#spring.cloud.gateway.routes[2].uri=lb://question-service
#spring.cloud.gateway.routes[2].predicates[0]=Path=/question-service/**
#
#spring.cloud.gateway.routes[3].id=user-service
#spring.cloud.gateway.routes[3].uri=lb://user-service
#spring.cloud.gateway.routes[3].predicates[0]=Path=/user-service/**


#anything: hasan
#
#

server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quiz/**
          filters:
            - name: JwtAuthorizationFilter # Apply JWT filter to this route
            - name: RequestHeaderToRequestUri
              args:
                role: "admin"

        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
          filters:
            - name: JwtAuthorizationFilter # Apply JWT filter to this route
            - name: RequestHeaderToRequestUri
              args:
                role: "admin"

        - id: submission-service
          uri: lb://submission-service
          predicates:
            - Path=/submission/**
          filters:
            - name: JwtAuthorizationFilter # Apply JWT filter to this route
            - name: RequestHeaderToRequestUri
              args:
                role: "user"

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: JwtAuthorizationFilter # Apply JWT filter to this route
            - name: RequestHeaderToRequestUri
              args:
                role: "user"


#  datasource:
#    url: jdbc:mysql://localhost:3306/user_service
#    username: root
#    password: Bigdev@99
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#
#  jpa:
#    hibernate:
#      ddl-auto: update
